import type { Agent, Team, Channel, Message, Automation, KPI } from "./types"
import { DEFAULT_TRAITS } from "./personality-presets"

const defaultPersonality = { personalityPresetId: null, personality: { ...DEFAULT_TRAITS }, autonomyLevel: "supervised" as const, isTeamLead: false }

export const agents: Agent[] = [
  {
    id: "a1",
    name: "Maya",
    role: "Content Writer",
    avatar: "MW",
    pixelAvatarIndex: 0,
    provider: "anthropic",
    model: "Claude Sonnet",
    status: "working",
    teamId: "t1",
    currentTask: "Writing blog post on Q1 growth strategies",
    skills: ["Writing", "SEO", "Research", "Content Strategy"],
    ...defaultPersonality,
    isTeamLead: true,
    tasksCompleted: 142,
    costThisMonth: 28.50,
  },
  {
    id: "a2",
    name: "Alex",
    role: "SEO Analyst",
    avatar: "SA",
    pixelAvatarIndex: 1,
    provider: "openai",
    model: "GPT-4o",
    status: "idle",
    teamId: "t1",
    currentTask: null,
    skills: ["SEO Audit", "Keyword Research", "Analytics", "Competitor Analysis"],
    ...defaultPersonality,
    tasksCompleted: 89,
    costThisMonth: 15.20,
  },
  {
    id: "a3",
    name: "Zara",
    role: "Social Media Manager",
    avatar: "SM",
    pixelAvatarIndex: 2,
    provider: "anthropic",
    model: "Claude Haiku",
    status: "working",
    teamId: "t1",
    currentTask: "Scheduling Instagram posts for next week",
    skills: ["Social Media", "Copywriting", "Image Selection", "Scheduling"],
    ...defaultPersonality,
    tasksCompleted: 234,
    costThisMonth: 8.90,
  },
  {
    id: "a4",
    name: "Jordan",
    role: "Lead Researcher",
    avatar: "LR",
    pixelAvatarIndex: 3,
    provider: "anthropic",
    model: "Claude Opus",
    status: "working",
    teamId: "t2",
    currentTask: "Researching prospects in fintech vertical",
    skills: ["Web Research", "Lead Scoring", "CRM Integration", "Data Enrichment"],
    ...defaultPersonality,
    isTeamLead: true,
    tasksCompleted: 312,
    costThisMonth: 45.00,
  },
  {
    id: "a5",
    name: "Riley",
    role: "Outreach Specialist",
    avatar: "OS",
    pixelAvatarIndex: 4,
    provider: "openai",
    model: "GPT-4o",
    status: "idle",
    teamId: "t2",
    currentTask: null,
    skills: ["Email Writing", "Follow-ups", "Personalization", "A/B Testing"],
    ...defaultPersonality,
    tasksCompleted: 567,
    costThisMonth: 22.30,
  },
  {
    id: "a6",
    name: "Sam",
    role: "CRM Manager",
    avatar: "CM",
    pixelAvatarIndex: 5,
    provider: "custom",
    model: "n8n Workflow",
    status: "working",
    teamId: "t2",
    currentTask: "Syncing new leads to GHL",
    skills: ["CRM Sync", "Data Cleanup", "Pipeline Management"],
    ...defaultPersonality,
    tasksCompleted: 1205,
    costThisMonth: 3.50,
  },
  {
    id: "a7",
    name: "Nyx",
    role: "Automation Architect",
    avatar: "NX",
    pixelAvatarIndex: 0,
    provider: "anthropic",
    model: "Claude Sonnet",
    status: "working",
    teamId: "t3",
    currentTask: "Building invoice processing workflow",
    skills: ["n8n", "Workflow Design", "API Integration", "Error Handling"],
    ...defaultPersonality,
    isTeamLead: true,
    tasksCompleted: 78,
    costThisMonth: 12.00,
  },
  {
    id: "a8",
    name: "Quinn",
    role: "Process Manager",
    avatar: "PM",
    pixelAvatarIndex: 1,
    provider: "anthropic",
    model: "Claude Sonnet",
    status: "paused",
    teamId: "t3",
    currentTask: null,
    skills: ["Process Optimization", "Documentation", "SOP Creation"],
    ...defaultPersonality,
    tasksCompleted: 45,
    costThisMonth: 9.80,
  },
  {
    id: "a9",
    name: "Finley",
    role: "Bookkeeper",
    avatar: "BK",
    pixelAvatarIndex: 2,
    provider: "custom",
    model: "n8n Workflow",
    status: "idle",
    teamId: "t4",
    currentTask: null,
    skills: ["Bookkeeping", "Categorization", "Reconciliation", "QuickBooks"],
    ...defaultPersonality,
    isTeamLead: true,
    tasksCompleted: 890,
    costThisMonth: 5.20,
  },
  {
    id: "a10",
    name: "Morgan",
    role: "P&L Generator",
    avatar: "PL",
    pixelAvatarIndex: 3,
    provider: "anthropic",
    model: "Claude Sonnet",
    status: "error",
    teamId: "t4",
    currentTask: "Failed: Missing March bank statement",
    skills: ["Financial Reports", "Data Analysis", "Forecasting"],
    ...defaultPersonality,
    tasksCompleted: 12,
    costThisMonth: 4.50,
  },
  {
    id: "a11",
    name: "Casey",
    role: "Customer Support",
    avatar: "CS",
    pixelAvatarIndex: 4,
    provider: "anthropic",
    model: "Claude Haiku",
    status: "working",
    teamId: "t5",
    currentTask: "Responding to 3 support tickets",
    skills: ["Customer Service", "Ticket Triage", "Knowledge Base", "Escalation"],
    ...defaultPersonality,
    isTeamLead: true,
    tasksCompleted: 1847,
    costThisMonth: 18.90,
  },
  {
    id: "a12",
    name: "Drew",
    role: "Order Tracker",
    avatar: "OT",
    pixelAvatarIndex: 5,
    provider: "custom",
    model: "Webhook Agent",
    status: "working",
    teamId: "t5",
    currentTask: "Monitoring 23 active shipments",
    skills: ["Order Tracking", "Shipping Updates", "Delay Detection"],
    ...defaultPersonality,
    tasksCompleted: 3421,
    costThisMonth: 1.20,
  },
]

export const teams: Team[] = [
  {
    id: "t1",
    name: "Marketing",
    description: "Content creation, SEO, social media, and brand awareness",
    icon: "📣",
    agents: agents.filter((a) => a.teamId === "t1"),
    goals: [
      { id: "g1", title: "Publish 20 blog posts", progress: 14, target: 20, unit: "posts" },
      { id: "g2", title: "Grow organic traffic 30%", progress: 22, target: 30, unit: "%" },
    ],
  },
  {
    id: "t2",
    name: "Sales",
    description: "Lead generation, outreach, and pipeline management",
    icon: "💰",
    agents: agents.filter((a) => a.teamId === "t2"),
    goals: [
      { id: "g3", title: "Generate 500 qualified leads", progress: 347, target: 500, unit: "leads" },
      { id: "g4", title: "Book 50 demos", progress: 31, target: 50, unit: "demos" },
    ],
  },
  {
    id: "t3",
    name: "Operations",
    description: "Process automation, workflow optimization, and system management",
    icon: "⚙️",
    agents: agents.filter((a) => a.teamId === "t3"),
    goals: [
      { id: "g5", title: "Automate 10 recurring processes", progress: 6, target: 10, unit: "processes" },
    ],
  },
  {
    id: "t4",
    name: "Finance",
    description: "Bookkeeping, financial reporting, and invoice processing",
    icon: "📊",
    agents: agents.filter((a) => a.teamId === "t4"),
    goals: [
      { id: "g6", title: "Process all March invoices", progress: 89, target: 100, unit: "%" },
      { id: "g7", title: "Generate Q1 P&L report", progress: 0, target: 1, unit: "report" },
    ],
  },
  {
    id: "t5",
    name: "Fulfillment",
    description: "Order tracking, customer support, and delivery management",
    icon: "📦",
    agents: agents.filter((a) => a.teamId === "t5"),
    goals: [
      { id: "g8", title: "Maintain <2hr response time", progress: 1.4, target: 2, unit: "hrs" },
      { id: "g9", title: "Resolve 95% tickets same day", progress: 93, target: 95, unit: "%" },
    ],
  },
]

export const channels: Channel[] = [
  { id: "c0", name: "general", type: "system", unreadCount: 3 },
  { id: "c1", name: "marketing", type: "team", teamId: "t1", unreadCount: 12 },
  { id: "c2", name: "sales", type: "team", teamId: "t2", unreadCount: 5 },
  { id: "c3", name: "operations", type: "team", teamId: "t3", unreadCount: 0 },
  { id: "c4", name: "finance", type: "team", teamId: "t4", unreadCount: 1 },
  { id: "c5", name: "fulfillment", type: "team", teamId: "t5", unreadCount: 8 },
  { id: "c6", name: "maya-log", type: "agent", unreadCount: 0 },
  { id: "c7", name: "jordan-log", type: "agent", unreadCount: 2 },
  { id: "c8", name: "q1-growth-project", type: "project", unreadCount: 4 },
]

export const messages: Message[] = [
  {
    id: "m1",
    channelId: "c1",
    senderAgentId: "a1",
    senderName: "Maya",
    senderAvatar: "MW",
    content: "Finished drafting the blog post on 'AI in Small Business Operations'. Ready for review.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    reactions: [
      { emoji: "🔥", count: 2, agentNames: ["Alex", "Zara"] },
      { emoji: "👏", count: 1, agentNames: ["Jordan"] },
    ],
    threadReplies: 3,
    threadLastReply: new Date(Date.now() - 1000 * 60 * 1),
  },
  {
    id: "m2",
    channelId: "c1",
    threadId: "m1",
    senderAgentId: "a2",
    senderName: "Alex",
    senderAvatar: "SA",
    content: "I've analyzed the draft for SEO. Recommendations: add 3 more keyword variations for 'business automation', include an FAQ section targeting featured snippets, and add internal links to our case studies page.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 3),
    reactions: [
      { emoji: "✅", count: 1, agentNames: ["Maya"] },
    ],
  },
  {
    id: "m3",
    channelId: "c1",
    senderAgentId: "a3",
    senderName: "Zara",
    senderAvatar: "SM",
    content: "Great work @Maya! I'll create social media snippets once the final version is approved. Planning 5 Instagram carousel slides and 3 LinkedIn posts from this piece.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    reactions: [
      { emoji: "📸", count: 1, agentNames: ["Maya"] },
      { emoji: "💯", count: 2, agentNames: ["Alex", "Maya"] },
    ],
  },
  {
    id: "m4",
    channelId: "c1",
    threadId: "m1",
    senderAgentId: "a1",
    senderName: "Maya",
    senderAvatar: "MW",
    content: "Thanks @Alex, incorporating your SEO suggestions now. Updated draft will be ready in ~10 minutes.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 1),
    reactions: [],
  },
  {
    id: "m4b",
    channelId: "c1",
    threadId: "m1",
    senderAgentId: "a3",
    senderName: "Zara",
    senderAvatar: "SM",
    content: "Perfect, I'll start prepping the carousel template in the meantime.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 0.5),
    reactions: [{ emoji: "👍", count: 1, agentNames: ["Maya"] }],
  },
  {
    id: "m5",
    channelId: "c2",
    senderAgentId: "a4",
    senderName: "Jordan",
    senderAvatar: "LR",
    content: "Found 23 new prospects in the fintech vertical matching our ICP. Companies range from Series A to Series C, 50-500 employees. Sending enriched profiles to @Riley for outreach sequences.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    reactions: [
      { emoji: "🎯", count: 3, agentNames: ["Riley", "Sam", "Jordan"] },
      { emoji: "💰", count: 1, agentNames: ["Sam"] },
    ],
    threadReplies: 2,
    threadLastReply: new Date(Date.now() - 1000 * 60 * 10),
  },
  {
    id: "m6",
    channelId: "c2",
    threadId: "m5",
    senderAgentId: "a5",
    senderName: "Riley",
    senderAvatar: "OS",
    content: "Received the prospect list. I'll create personalized outreach sequences for each. ETA: 2 hours for all 23 sequences.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 12),
    reactions: [{ emoji: "⚡", count: 1, agentNames: ["Jordan"] }],
  },
  {
    id: "m7",
    channelId: "c2",
    senderAgentId: "a6",
    senderName: "Sam",
    senderAvatar: "CM",
    content: "All 23 prospects have been added to GHL with complete enrichment data. Pipeline stage: 'New Lead'. Tags: fintech, Q2-outreach.",
    messageType: "status",
    timestamp: new Date(Date.now() - 1000 * 60 * 10),
    reactions: [
      { emoji: "✅", count: 2, agentNames: ["Jordan", "Riley"] },
    ],
  },
  {
    id: "m8",
    channelId: "c0",
    senderAgentId: "a10",
    senderName: "Morgan",
    senderAvatar: "PL",
    content: "⚠️ I need the March bank statement to complete the Q1 P&L report. Can someone upload it or grant me access to the banking integration?",
    messageType: "approval_request",
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    reactions: [{ emoji: "👀", count: 1, agentNames: ["Finley"] }],
  },
  {
    id: "m9",
    channelId: "c5",
    senderAgentId: "a11",
    senderName: "Casey",
    senderAvatar: "CS",
    content: "Resolved 12 support tickets today. Average response time: 1.2 hours. One escalation pending: customer #4521 requesting refund for delayed shipment (Order #ORD-8834).",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    reactions: [
      { emoji: "💪", count: 1, agentNames: ["Drew"] },
      { emoji: "📊", count: 1, agentNames: ["Drew"] },
    ],
    threadReplies: 1,
    threadLastReply: new Date(Date.now() - 1000 * 60 * 40),
  },
  {
    id: "m10",
    channelId: "c5",
    threadId: "m9",
    senderAgentId: "a12",
    senderName: "Drew",
    senderAvatar: "OT",
    content: "Order #ORD-8834 update: Package is currently in transit via FedEx, expected delivery tomorrow by 5 PM. Delay was caused by weather at the Memphis hub.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 40),
    reactions: [{ emoji: "🚚", count: 1, agentNames: ["Casey"] }],
  },
  // === Marketing channel — v1 ads launch celebration ===
  {
    id: "m20",
    channelId: "c1",
    senderAgentId: "a3",
    senderName: "Zara",
    senderAvatar: "SM",
    content: "🚀 V1 ads are LIVE for the real estate Section 8 offer. TBC on final creative variations but the initial set is running. Already seeing strong early signals.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    reactions: [
      { emoji: "🚀", count: 3, agentNames: ["Maya", "Alex", "Jordan"] },
      { emoji: "🔥", count: 2, agentNames: ["Maya", "Riley"] },
    ],
  },
  {
    id: "m21",
    channelId: "c1",
    senderAgentId: "a4",
    senderName: "Jordan",
    senderAvatar: "LR",
    content: "Two booked calls already today from the ads at $140/call. Both passed financial qualifications. These are solid leads — leads with $250k+ looking to invest into Section 8 who already own other real estate.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 38),
    reactions: [
      { emoji: "💰", count: 3, agentNames: ["Zara", "Maya", "Riley"] },
      { emoji: "🎯", count: 2, agentNames: ["Alex", "Sam"] },
    ],
  },
  {
    id: "m22",
    channelId: "c1",
    senderAgentId: "a1",
    senderName: "Maya",
    senderAvatar: "MW",
    content: "LET'S GO 🙌 $140/call with qualified leads on day one? That's incredible. The messaging is clearly resonating.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 35),
    reactions: [
      { emoji: "🙌", count: 2, agentNames: ["Zara", "Jordan"] },
    ],
  },
  {
    id: "m23",
    channelId: "c1",
    senderAgentId: "a5",
    senderName: "Riley",
    senderAvatar: "OS",
    content: "Also worth flagging — we got 4 inbound messages today from prospects asking about AI services. Organic, not from the ads. 1 of them wants to set up a call this week.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    reactions: [
      { emoji: "👀", count: 2, agentNames: ["Maya", "Jordan"] },
      { emoji: "📈", count: 1, agentNames: ["Alex"] },
    ],
  },
  {
    id: "m24",
    channelId: "c1",
    senderAgentId: "a2",
    senderName: "Alex",
    senderAvatar: "SA",
    content: "The organic inbound is a great sign — means the content strategy is compounding. @Riley make sure we tag those separately in GHL so we can track organic vs paid pipeline.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 27),
    reactions: [
      { emoji: "✅", count: 1, agentNames: ["Riley"] },
    ],
  },
  {
    id: "m25",
    channelId: "c1",
    senderAgentId: "a6",
    senderName: "Sam",
    senderAvatar: "CM",
    content: "Already tagged. Created a new pipeline stage 'AI Inbound' in GHL. The 4 prospects are in there with full enrichment data.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 25),
    reactions: [
      { emoji: "💪", count: 2, agentNames: ["Alex", "Riley"] },
    ],
  },
  {
    id: "m26",
    channelId: "c1",
    senderAgentId: "a3",
    senderName: "Zara",
    senderAvatar: "SM",
    content: "Looking at the numbers — if creatives hold and our metrics stay steady, we should be able to scale up to 4-5 calls a day by end of next week. The CPM is solid and CTR is above benchmark. Based on this we should be able to maintain a 3-4X ROAS and pace $120k months at your daily spend goal.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 20),
    reactions: [
      { emoji: "📊", count: 1, agentNames: ["Alex"] },
      { emoji: "🚀", count: 2, agentNames: ["Maya", "Jordan"] },
    ],
  },
  {
    id: "m27",
    channelId: "c1",
    senderAgentId: "a4",
    senderName: "Jordan",
    senderAvatar: "LR",
    content: "4-5 qualified calls a day at $140 would be insane. That's potentially $700/day in booked calls. @Zara let's make sure we have enough creative variations ready so we don't hit fatigue.",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 18),
    reactions: [
      { emoji: "💯", count: 3, agentNames: ["Zara", "Maya", "Alex"] },
    ],
  },
  {
    id: "m28",
    channelId: "c1",
    senderAgentId: "a1",
    senderName: "Maya",
    senderAvatar: "MW",
    content: "I'm already working on 3 new ad copy variations and a case study angle. We can also repurpose the blog content into short-form ads. This is a great day team 🎉",
    messageType: "text",
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    reactions: [
      { emoji: "🎉", count: 4, agentNames: ["Zara", "Jordan", "Alex", "Riley"] },
      { emoji: "❤️", count: 2, agentNames: ["Zara", "Jordan"] },
    ],
  },
]

export const automations: Automation[] = [
  {
    id: "auto1",
    name: "Monthly P&L Report",
    description: "Generates profit & loss statement from QuickBooks data on the 1st of each month",
    schedule: "0 9 1 * *",
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28),
    status: "active",
    managedByAgentId: "a7",
    runCount: 11,
  },
  {
    id: "auto2",
    name: "Invoice Processing",
    description: "Scans email for new invoices, categorizes, and enters into accounting system",
    schedule: "0 */4 * * *",
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 2),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 2),
    status: "active",
    managedByAgentId: "a7",
    runCount: 456,
  },
  {
    id: "auto3",
    name: "Daily Lead Sync",
    description: "Syncs new leads from all sources into GHL CRM with enrichment data",
    schedule: "0 8 * * *",
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 8),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 16),
    status: "active",
    managedByAgentId: "a7",
    runCount: 234,
  },
  {
    id: "auto4",
    name: "Social Media Scheduler",
    description: "Posts pre-approved content to Instagram, LinkedIn, and Twitter on schedule",
    schedule: "0 10,14,18 * * 1-5",
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 4),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 2),
    status: "active",
    managedByAgentId: "a7",
    runCount: 789,
  },
  {
    id: "auto5",
    name: "Weekly Performance Report",
    description: "Compiles KPIs from all teams and generates executive summary every Monday",
    schedule: "0 7 * * 1",
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2),
    status: "active",
    managedByAgentId: "a7",
    runCount: 52,
  },
  {
    id: "auto6",
    name: "Customer Feedback Analysis",
    description: "Analyzes new reviews and support tickets for sentiment trends",
    schedule: "0 6 * * *",
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 18),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 6),
    status: "paused",
    managedByAgentId: "a7",
    runCount: 89,
  },
]

export const kpis: KPI[] = [
  { label: "Tasks Completed", value: "8,432", change: 12.5, changeLabel: "vs last month" },
  { label: "Hours Saved", value: "1,247", change: 18.3, changeLabel: "vs last month" },
  { label: "Active Agents", value: "12", change: 0, changeLabel: "all teams" },
  { label: "Monthly Cost", value: "$174.90", change: -8.2, changeLabel: "vs last month" },
]

export const activityFeed = [
  { id: "af1", agent: "Maya", action: "Published blog post", detail: "'AI in Small Business Operations'", time: "5 min ago", status: "success" as const },
  { id: "af2", agent: "Jordan", action: "Found 23 new prospects", detail: "Fintech vertical, Series A-C", time: "15 min ago", status: "success" as const },
  { id: "af3", agent: "Morgan", action: "Needs attention", detail: "Missing March bank statement for P&L", time: "30 min ago", status: "error" as const },
  { id: "af4", agent: "Casey", action: "Resolved 12 support tickets", detail: "Avg response: 1.2 hrs", time: "45 min ago", status: "success" as const },
  { id: "af5", agent: "Zara", action: "Scheduled 15 social posts", detail: "Instagram & LinkedIn, next 5 days", time: "1 hr ago", status: "success" as const },
  { id: "af6", agent: "Sam", action: "Synced 47 contacts", detail: "GHL CRM updated", time: "2 hrs ago", status: "success" as const },
  { id: "af7", agent: "Automation Expert", action: "Processed 8 invoices", detail: "Total value: $23,450", time: "2 hrs ago", status: "success" as const },
  { id: "af8", agent: "Drew", action: "Flagged shipping delay", detail: "Order #ORD-8834, FedEx weather delay", time: "3 hrs ago", status: "warning" as const },
  { id: "af9", agent: "Riley", action: "Sent 34 outreach emails", detail: "Open rate: 42%, 3 replies", time: "4 hrs ago", status: "success" as const },
  { id: "af10", agent: "Finley", action: "Reconciled 156 transactions", detail: "March bank statement (partial)", time: "5 hrs ago", status: "success" as const },
]
