"use client"

import { useState, useEffect } from "react"
import { X, Mail, Copy, Check, Calendar } from "lucide-react"

// ── Types ────────────────────────────────────────────────────

interface Agent {
  id: string
  name: string
  role: string
  status: string
  tasksCompleted: number
  costThisMonth: number
  currentTask: string | null
}

interface Task {
  id: string
  title: string
  status: string
  description: string | null
  assigneeId: string | null
  createdAt: string
}

interface ActivityEntry {
  id: string
  agentName: string
  action: string
  description: string
  createdAt: string
}

// ── Helpers ──────────────────────────────────────────────────

function todayLabel(): string {
  return new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  })
}

function buildPlainText(
  agents: Agent[],
  tasks: Task[],
  activity: ActivityEntry[]
): string {
  const totalTasks = agents.reduce((s, a) => s + (a.tasksCompleted ?? 0), 0)
  const hoursSaved = Math.round(totalTasks * 0.15)
  const totalCost = agents.reduce((s, a) => s + (a.costThisMonth ?? 0), 0)
  const activeAgents = agents.filter((a) => a.status === "working").length
  const doneTasks = tasks.filter((t) => t.status === "done")
  const blockers = tasks.filter(
    (t) => t.description?.toLowerCase().includes("blocked") || t.status === "blocked"
  )
  const inProgress = tasks.filter((t) => t.status === "in_progress" || t.status === "review")
  const highlights = activity.slice(0, 5)

  const lines: string[] = []

  lines.push(`DAILY DIGEST — ${todayLabel()}`)
  lines.push("=".repeat(40))
  lines.push("")

  lines.push("EXECUTIVE SUMMARY")
  lines.push(
    `Your team of ${agents.length} agents completed ${totalTasks} tasks today, saving an estimated ${hoursSaved} hours. ${activeAgents} agents are currently active, with a total spend of $${totalCost.toFixed(2)}.`
  )
  lines.push("")

  if (highlights.length > 0) {
    lines.push("HIGHLIGHTS")
    highlights.forEach((h) => {
      lines.push(`  - ${h.agentName}: ${h.description}`)
    })
    lines.push("")
  }

  if (doneTasks.length > 0) {
    lines.push("TASKS COMPLETED")
    doneTasks.slice(0, 10).forEach((t) => {
      const agent = agents.find((a) => a.id === t.assigneeId)
      lines.push(`  - ${t.title}${agent ? ` (${agent.name})` : ""}`)
    })
    lines.push("")
  }

  if (blockers.length > 0) {
    lines.push("ACTIVE BLOCKERS")
    blockers.forEach((t) => {
      lines.push(`  - ${t.title}`)
    })
    lines.push("")
  }

  lines.push("COST TODAY")
  lines.push(`  $${totalCost.toFixed(2)} across ${agents.length} agents`)
  lines.push("")

  if (inProgress.length > 0) {
    lines.push("TOMORROW'S PRIORITIES")
    inProgress.slice(0, 5).forEach((t) => {
      lines.push(`  - ${t.title}`)
    })
    lines.push("")
  }

  lines.push("—")
  lines.push("Generated by VESPR")

  return lines.join("\n")
}

// ── Component ────────────────────────────────────────────────

export function DailyDigest({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [agents, setAgents] = useState<Agent[]>([])
  const [tasks, setTasks] = useState<Task[]>([])
  const [activity, setActivity] = useState<ActivityEntry[]>([])
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (!open) return
    setLoading(true)
    setCopied(false)
    Promise.all([
      fetch("/api/agents").then((r) => r.json()),
      fetch("/api/tasks?limit=100").then((r) => r.json()),
      fetch("/api/activity?limit=100").then((r) => r.json()),
    ])
      .then(([ag, tk, ac]) => {
        setAgents(ag as Agent[])
        setTasks((tk.tasks ?? tk) as Task[])
        setActivity((ac.entries ?? ac) as ActivityEntry[])
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [open])

  if (!open) return null

  const totalTasks = agents.reduce((s, a) => s + (a.tasksCompleted ?? 0), 0)
  const hoursSaved = Math.round(totalTasks * 0.15)
  const totalCost = agents.reduce((s, a) => s + (a.costThisMonth ?? 0), 0)
  const activeAgents = agents.filter((a) => a.status === "working").length
  const doneTasks = tasks.filter((t) => t.status === "done")
  const blockers = tasks.filter(
    (t) => t.description?.toLowerCase().includes("blocked") || t.status === "blocked"
  )
  const inProgress = tasks.filter((t) => t.status === "in_progress" || t.status === "review")
  const highlights = activity.slice(0, 5)

  const handleCopy = async () => {
    const text = buildPlainText(agents, tasks, activity)
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
      {/* Overlay click to close */}
      <div className="absolute inset-0" onClick={onClose} />

      <div className="relative z-10 bg-[#1a1a2e] border border-[rgba(255,255,255,0.08)] rounded-2xl shadow-2xl p-8 max-w-lg w-full max-h-[80vh] overflow-y-auto mx-4">
        {/* ── Toolbar ─────────────────────────────────── */}
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2">
            <Mail className="h-4 w-4 text-[#635bff]" />
            <span className="section-label">
              VESPR
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="text-[11px] text-[#635bff] hover:text-[#5b52e6] flex items-center gap-1 transition-colors"
            >
              {copied ? (
                <>
                  <Check className="h-3 w-3" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="h-3 w-3" />
                  Copy to clipboard
                </>
              )}
            </button>
            <button
              onClick={onClose}
              className="flex items-center justify-center h-7 w-7 rounded-lg hover:bg-[#16213e] transition-colors"
            >
              <X className="h-4 w-4 text-[#9ca3af]" />
            </button>
          </div>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <div className="text-sm text-[#6b7280] animate-pulse">
              Preparing your digest...
            </div>
          </div>
        ) : (
          <>
            {/* ── Date Header ────────────────────────── */}
            <div className="border-b border-[rgba(255,255,255,0.06)] pb-4 mb-6">
              <h1 className="text-lg font-semibold text-[#f3f4f6]">Daily Digest</h1>
              <p className="text-[11px] text-[#6b7280] mt-0.5">{todayLabel()}</p>
            </div>

            {/* ── Executive Summary ───────────────────── */}
            <section className="mb-6">
              <h2 className="section-label mb-2">
                Executive Summary
              </h2>
              <p className="text-xs text-[#9ca3af] leading-relaxed">
                Your team of {agents.length} agents completed {totalTasks} tasks today,
                saving an estimated {hoursSaved} hours. {activeAgents} agents are currently
                active, with a total spend of ${totalCost.toFixed(2)}.
              </p>
            </section>

            {/* ── KPI row ────────────────────────── */}
            <section className="mb-6 grid grid-cols-3 gap-3">
              <div className="bg-[#16213e] rounded-lg p-3 text-center">
                <p className="text-[22px] font-bold tabular-nums">{totalTasks}</p>
                <p className="text-[10px] text-[#6b7280] uppercase tracking-wider mt-0.5">Tasks</p>
              </div>
              <div className="bg-[#16213e] rounded-lg p-3 text-center">
                <p className="text-[22px] font-bold tabular-nums">{hoursSaved}h</p>
                <p className="text-[10px] text-[#6b7280] uppercase tracking-wider mt-0.5">Saved</p>
              </div>
              <div className="bg-[#16213e] rounded-lg p-3 text-center">
                <p className="text-[22px] font-bold tabular-nums">${totalCost.toFixed(0)}</p>
                <p className="text-[10px] text-[#6b7280] uppercase tracking-wider mt-0.5">Cost</p>
              </div>
            </section>

            {/* ── Highlights ─────────────────────────── */}
            {highlights.length > 0 && (
              <section className="mb-6">
                <h2 className="section-label mb-2">
                  Highlights
                </h2>
                <div className="divide-y divide-[rgba(255,255,255,0.04)]">
                  {highlights.map((entry) => (
                    <div
                      key={entry.id}
                      className="flex items-start gap-2 py-2 text-xs"
                    >
                      <span className="text-[rgba(255,255,255,0.35)] shrink-0 mt-0.5">-</span>
                      <span>
                        <span className="font-medium text-[#d1d5db]">{entry.agentName}</span>{" "}
                        <span className="text-[#6b7280]">{entry.description}</span>
                      </span>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* ── Tasks Completed ────────────────────── */}
            {doneTasks.length > 0 && (
              <section className="mb-6">
                <h2 className="section-label mb-2">
                  Tasks Completed
                </h2>
                <div className="divide-y divide-[rgba(255,255,255,0.04)]">
                  {doneTasks.slice(0, 10).map((task) => {
                    const agent = agents.find((a) => a.id === task.assigneeId)
                    return (
                      <div
                        key={task.id}
                        className="flex items-center gap-2 py-2 text-xs"
                      >
                        <span className="text-[#635bff] shrink-0">-</span>
                        <span className="flex-1 truncate text-[#d1d5db]">{task.title}</span>
                        {agent && (
                          <span className="text-[rgba(255,255,255,0.35)] shrink-0 text-[11px]">
                            {agent.name}
                          </span>
                        )}
                      </div>
                    )
                  })}
                </div>
              </section>
            )}

            {/* ── Active Blockers ────────────────────── */}
            {blockers.length > 0 && (
              <section className="mb-6">
                <h2 className="section-label mb-2">
                  Active Blockers
                </h2>
                <div className="space-y-1">
                  {blockers.map((task) => (
                    <div
                      key={task.id}
                      className="flex items-center gap-2 py-1 text-xs text-red-400"
                    >
                      <span className="shrink-0">-</span>
                      <span className="truncate">{task.title}</span>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* ── Cost Today ─────────────────────────── */}
            <section className="mb-6">
              <h2 className="section-label mb-2">
                Cost Today
              </h2>
              <p className="text-xs text-[#6b7280]">
                <span className="text-[#f3f4f6] font-bold tabular-nums">
                  ${totalCost.toFixed(2)}
                </span>{" "}
                across {agents.length} agents
              </p>
            </section>

            {/* ── Tomorrow's Priorities ──────────────── */}
            {inProgress.length > 0 && (
              <section className="mb-6">
                <h2 className="section-label mb-2">
                  Tomorrow&apos;s Priorities
                </h2>
                <div className="space-y-1">
                  {inProgress.slice(0, 5).map((task) => (
                    <div
                      key={task.id}
                      className="flex items-center gap-2 py-1 text-xs"
                    >
                      <span className="text-amber-500 shrink-0">-</span>
                      <span className="text-[#6b7280] truncate">{task.title}</span>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* ── Footer ─────────────────────────────── */}
            <div className="border-t border-[rgba(255,255,255,0.06)] pt-3 mt-2">
              <p className="text-[10px] text-[rgba(255,255,255,0.2)] text-center">
                Generated by VESPR on {todayLabel()}
              </p>
            </div>
          </>
        )}
      </div>
    </div>
  )
}

// ── Trigger Button ───────────────────────────────────────────

export function DailyDigestButton() {
  const [open, setOpen] = useState(false)

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="flex items-center gap-1.5 text-xs btn-secondary rounded-xl px-3 py-1.5"
      >
        <Calendar className="h-3 w-3 text-[#6b7280]" />
        <span className="text-[#9ca3af]">Daily Digest</span>
      </button>
      <DailyDigest open={open} onClose={() => setOpen(false)} />
    </>
  )
}
